name: asdf
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  easy_splash_screen: ^1.0.4
  connectivity_plus: ^5.0.1
  url_launcher: ^6.0.0
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^16.1.0
  restart_app: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/


  uses-material-design: true
